apiVersion: v1
kind: Service
metadata:
  name: employee-attrition-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: employee-attrition-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }} 