{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rag-{{ .Release.Name }}-netpol
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: rag-vector-store
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    {{- if .Values.networkPolicy.allowedNamespaces }}
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            {{- toYaml .Values.networkPolicy.allowedNamespaces | nindent 12 }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
{{- end }} 