replicaCount: 1

image:
  repository: techiescamp/rag-backend
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

config:
  azureEndpoint: "<open-ai-endpoint>"
  azureChatDeployment: "gpt-4o-mini"
  openaiApiVersion: "2024-05-01-preview"
  azureEmbeddingDeployment: "text-embedding-3-small"
  azureEmbeddingVersion: "2024-12-01-preview"

secret:
  azureApiKey: "<open-ai-api-key>"