apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-attrition-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: employee-attrition-backend
  template:
    metadata:
      labels:
        app: employee-attrition-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: FEAST_SERVER_URL
              value: {{ .Values.env.FEAST_SERVER_URL | quote }}
            - name: KSERVE_URL
              value: {{ .Values.env.KSERVE_URL | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }} 