apiVersion: v1
kind: Service
metadata:
  name: employee-attrition-backend
  namespace: kserve
spec:
  selector:
    app: employee-attrition-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP