apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-attrition-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PREDICTION_URL
              value: {{ .Values.env.PREDICTION_URL | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }} 