apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.azureStorageConnectionString | quote }} 