apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mlops-employee-attrition
  namespace: kserve
spec:
  predictor:
    containers:
      - name: predictor
        image: techiescamp/custom-kserve:4.0.0
        env:
          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: azure-storage-secret
                key: AZURE_STORAGE_CONNECTION_STRING
          - name: MLFLOW_TRACKING_URI
            value: "http://mlflow.mlflow.svc.cluster.local:5000"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
