apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-ui
  labels:
    app: rag-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-ui
  template:
    metadata:
      labels:
        app: rag-ui
    spec:
      containers:
      - name: attrition-ui
        image: techiescamp/rag-frontend:2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: REACT_APP_API_URL
          value: "http://rag-backend-service.default.svc.cluster.local:8000"