apiVersion: v1
kind: Service
metadata:
  name: rag-ui
  namespace: default
spec:
  selector:
    app: rag-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30500
  type: NodePort