apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mlops-employee-attrition
  namespace: {{ .Release.Namespace }}
spec:
  predictor:
    containers:
      - name: predictor
        image: {{ .Values.image }}
        env:
          - name: AZURE_STORAGE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: azure-storage-secret
                key: AZURE_STORAGE_CONNECTION_STRING
          - name: MLFLOW_TRACKING_URI
            value: {{ .Values.env.MLFLOW_TRACKING_URI | quote }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }} 