apiVersion: v1
kind: Service
metadata:
  name: rag-backend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: rag-backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}