version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm_backend_node_app
    ports:
      - "9090:5000"
    volumes:
      - ./uploads:/usr/src/app/uploads
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
