version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "7000:7000"
    volumes:
      - ./uploads:/usr/src/app/uploads
    environment:
      - NODE_ENV=production
    restart: unless-stopped
