apiVersion: v1
kind: ConfigMap
metadata:
    name: rag-{{ .Release.Namespace }}-configmap
    namespace: {{ .Release.Namespace }}
data:
    AZURE_ENDPOINT: {{ .Values.config.azureEndpoint }}
    AZURE_CHAT_DEPLOYMENT: {{ .Values.config.azureChatDeployment }}
    AZURE_OPENAI_API_VERSION: {{ .Values.config.openaiApiVersion }}
    VECTOR_DB_URL: {{ .Values.config.vectorStoreUrl }}
    HOST: "0.0.0.0"
    PORT: "8000"