apiVersion: v1
kind: ConfigMap
metadata:
    name: rag-{{ .Release.Name }}-configmap
    namespace: {{ .Release.Namespace }}
data:
    AZURE_ENDPOINT: {{ .Values.config.azureOpenAIEndpoint }}
    AZURE_CHAT_DEPLOYMENT: {{ .Values.config.azureOpenAIllmModel }}
    AZURE_OPENAI_API_VERSION: {{ .Values.config.azureOpenAIllmModelVersion }}
    VECTOR_DB_URL: {{ .Values.config.vectorStoreUrl }}
    HOST: "0.0.0.0"
    PORT: "8000"