apiVersion: v1
kind: Secret
metadata:
    name: rag-{{ .Release.Namespace }}-secret
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
    AZURE_API_KEY: {{ .Values.secret.azureApiKey | b64enc | quote }}