apiVersion: v1
kind: Secret
metadata:
    name: rag-{{ .Release.Name }}-secret
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
    AZURE_API_KEY: {{ .Values.secret.azureOpenAIApiKey | b64enc }}