apiVersion: v1
kind: ConfigMap
metadata:
    name: rag-{{ .Release.Name }}-configmap
    namespace: {{ .Release.Namespace }}
data:
    AZURE_ENDPOINT: {{ .Values.config.azureEndpoint }}
    AZURE_EMBEDDING_DEPLOYMENT: {{ .Values.config.azureEmbeddingDeployment }}
    AZURE_EMBEDDING_VERSION: {{ .Values.config.azureEmbeddingVersion }}
    K8_URL: {{ .Values.config.k8sUrl }}
    VECTOR_DB_URL: {{ .Values.config.vectorStoreUrl }}