apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector-store
spec:
  serviceName: "vector-store"
  replicas: 1
  selector:
    matchLabels:
      app: vector-store
  template:
    metadata:
      labels:
        app: vector-store
    spec:
      containers:
        - name: vector-store
          image: techiescamp/rag-vector-store:1.0.0
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: vector-store-env
          env:
            - name: AZURE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: vector-store-secret
                  key: AZURE_API_KEY
  volumeClaimTemplates:
    - metadata:
        name: vector-store-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
        storageClassName: default
