name: RAG Chatbot Pipeline

on:
  workflow_dispatch:

jobs:
  run-chatbot:
    runs-on: mlops
    defaults:
      run:
        working-directory: rag_chatbot

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create .env file from GitHub Secrets
        run: |
          echo "AZURE_ENDPOINT=${{ secrets.AZURE_ENDPOINT }}" >> .env
          echo "AZURE_API_KEY=${{ secrets.AZURE_API_KEY }}" >> .env
          echo "AZURE_DEPLOYMENT=gpt-4o-mini" >> .env
          echo "OPENAI_API_VERSION=2024-05-01-preview" >> .env
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> .env

      - name: Start and Test FastAPI App
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5
          curl --fail http://localhost:8000/docs || exit 1