replicaCount: 1

image:
  repository: techiescamp/rag-frontend
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 30500

backend_url: "http://rag-backend-service.default.svc.cluster.local:8000"